# Generated by Django 6.0.3 on 2026-05-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_paymenttransaction_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('UPI', 'UPI / GPay'), ('STRIPE', 'Stripe'), ('DEMO', 'Demo')], default='DEMO', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment_id / UPI txn ref', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
