# Generated by Django 6.0.3 on 2026-03-05 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='E.164 format: +1234567890', max_length=30)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='contact_avatars/')),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'phone_number'], name='whatsapp_co_organiz_a79c11_idx'), models.Index(fields=['organization', 'is_blocked'], name='whatsapp_co_organiz_eb25b2_idx')],
                'unique_together': {('organization', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text="Friendly name e.g. 'Support Line'", max_length=255)),
                ('phone_number_id', models.CharField(help_text='WhatsApp Cloud API phone_number_id', max_length=150, unique=True)),
                ('whatsapp_business_account_id', models.CharField(max_length=150)),
                ('access_token', models.TextField(help_text='Graph API permanent access token')),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['phone_number_id'], name='whatsapp_wh_phone_n_df62b6_idx'), models.Index(fields=['organization', 'is_active'], name='whatsapp_wh_organiz_10e298_idx')],
            },
        ),
    ]
