# Generated by Django 6.0.3 on 2026-04-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='display_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
