# Generated by Django 6.0.3 on 2026-03-05 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationFlow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger_keyword', models.CharField(help_text="Keyword that starts this flow (e.g. 'hello', 'start')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('flow_data', models.JSONField(default=dict, help_text='Flow definition. Example: {"steps": [{"id": "welcome", "message": "Hello!", "options": [{"text": "1. Products", "next_step": "products"}, {"text": "2. Support", "next_step": "support"}]}]}')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('whatsapp_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='whatsapp.whatsappaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.JSONField(default=list, help_text='List of keywords/phrases that trigger this rule (case-insensitive)')),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('exact', 'Exact Match'), ('starts_with', 'Starts With')], default='contains', max_length=20)),
                ('reply_text', models.TextField(help_text='Text message to send as reply')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority rules are checked first')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('whatsapp_accounts', models.ManyToManyField(blank=True, related_name='automation_rules', to='whatsapp.whatsappaccount')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactFlowSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step_id', models.CharField(max_length=100)),
                ('is_complete', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_sessions', to='whatsapp.contact')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='automation.automationflow')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='automationflow',
            index=models.Index(fields=['organization', 'is_active'], name='automation__organiz_060d97_idx'),
        ),
        migrations.AddIndex(
            model_name='automationflow',
            index=models.Index(fields=['trigger_keyword'], name='automation__trigger_36f05b_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['organization', 'is_active'], name='automation__organiz_3f1cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='contactflowsession',
            index=models.Index(fields=['contact', 'is_complete'], name='automation__contact_529d76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactflowsession',
            unique_together={('contact', 'flow')},
        ),
    ]
