# Generated by Django 5.0.4 on 2026-05-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='used',
            new_name='is_used',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='expires_at',
        ),
    ]
